question_data = [
    {"category": "Entertainment: Music",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The music video to The Buggle&#039;s &quot;Video Killed the Radio Star&quot; was the fir"
                 "st music video to broadcast on MTV.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Politics",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In 2016, the United Kingdom voted to stay in the EU.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "General Knowledge",
     "type": "multiple",
     "difficulty": "hard",
     "question": "Which film star has his statue in Leicester Square?",
     "correct_answer": "Charlie Chaplin",
     "incorrect_answers": ["Paul Newman", "Rowan Atkinson ", "Alfred Hitchcock"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Musicals & Theatres", "type": "multiple", "difficulty": "hard",
     "question": "Who wrote the lyrics for Leonard Bernstein&#039;s 1957 Brodway musical West Side Story?",
     "correct_answer": "Stephen Sondheim", "incorrect_answers": ["Himself", "Oscar Hammerstein", "Richard Rodgers"]},
    {"category": "Politics", "type": "multiple", "difficulty": "hard",
     "question": "Which of the following United States Presidents served the shortest term in office?",
     "correct_answer": "William Henry Harrison",
     "incorrect_answers": ["Zachary Taylor", "James A. Garfield", "Warren G. Harding"]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "easy",
     "question": "What was Daft Punk&#039;s first studio album?", "correct_answer": "Homework",
     "incorrect_answers": ["Discovery", "Random Access Memories", "Human After All"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "Which character from the Mega Man series made a small cameo on Volt Catfish&#039;s introduction scene in CD versions of Mega Man X3?",
     "correct_answer": "Auto", "incorrect_answers": ["Eddie", "Tango", "Rush"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "hard",
     "question": "If someone said &quot;you are olid&quot;, what would they mean?",
     "correct_answer": "You smell extremely unpleasant.",
     "incorrect_answers": ["You are out of shape\/weak.", "Your appearance is repulsive.",
                           "You are incomprehensible\/an idiot."]},
    {"category": "Entertainment: Music", "type": "multiple", "difficulty": "hard",
     "question": "Pamina and Papageno are characters in what Mozart opera?", "correct_answer": "The Magic Flute",
     "incorrect_answers": ["The Marriage of Figaro", "The Impresario", "The Goose of Cairo"]}
]
